name: Artifacts
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    #branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: main
        run: |
          mkdir -p artifacts
          TMPFILE=$(mktemp)
          for f in *.csv;do (tail -n +2 -q "${f}";echo) >> $TMPFILE;done
          sort -uf $TMPFILE | sed -e '1s/^/Account address,Show boosts/' -e 's/\r//' -e 's/^[[:space:]]*$//' > aws-all.csv
          cp *.csv artifacts/
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: AWS-Mastodon-Lists
          path: artifacts/
